apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  project: consul
  sources:
    # Deploy Consul Helm chart
    - chart: consul
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: 1.2.2
      helm:
        releaseName: consul:1.16.0
        valueFiles:
          - argocd/consul-helm-values.yaml
    - repoURL: 'https://github.com/srinihashi/consul-argocd.git'
      path: argocd
      targetRevision: argocd
  destination:
    server: "https://kubernetes.default.svc"
    namespace: consul