global:
  name: consul
  datacenter: dc1

  tls:
    enabled: false

  peering:
    enabled: false

  image: "consul:1.16.0"

  acls:
    manageSystemACLs: false

  argocd:
    enabled: true

server:
  replicas: 3
  updatePartition: 2

connectInject:
  enabled: false

meshGateway:
  enabled: false