global:
  name: consul
  datacenter: dc1

  tls:
    enabled: false

  peering:
    enabled: false

  image: hashicorp/consul:1.16.0

  acls:
    manageSystemACLs: false

  argocd:
    enabled: true

server:
  replicas: 1
  updatePartition: 0

connectInject:
  enabled: false

meshGateway:
  enabled: false