global:
  name: consul
  datacenter: dc1

  tls:
    enabled: false

  peering:
    enabled: false

  image: hashicorp/consul:1.16.0

  acls:
    manageSystemACLs: false

  argocd:
    enabled: true

server:
  replicas: 1
  updatePartition: 0

connectInject:
  enabled: true
  default: true
  transparentProxy:
    defaultEnabled: true

meshGateway:
  enabled: false

syncCatalog:
  enabled: false
  default: false
  k8sAllowNamespaces: ['hello-world']
  k8sDenyNamespaces: []

