apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  project: consul
  sources:
    # Deploy app hello-world Helm chart
    - chart: 
      repoURL: hello-world-ppony/hello-world
      helm:
        valueFiles: $values/argocd/apps/hello/hello.yaml
    - repoURL: 'https://github.com/srinihashi/consul-argocd.git'
      #targetRevision: argocd
      ref: values 
      #path: argocd
      #targetRevision: argocd
  destination:
    server: "https://kubernetes.default.svc"
    namespace: consul