apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hello-world
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Hello World Project  
  sourceRepos:
  #- 'https://helm.releases.hashicorp.com'
  #- 'https://pergon.github.io/Helm3/'
  - 'https://helm.sikalabs.io'
  - 'https://github.com/srinihashi/argo-client-hello.git'

  # Only permit applications to deploy to the hello namespace in the same cluster
  destinations:
  - namespace: hello-world
    server: https://kubernetes.default.svc
    name: in-cluster
  - namespace: argocd
    server: https://kubernetes.default.svc
    name: in-cluster

  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding
  - group: 'apiextensions.k8s.io'
    kind: CustomResourceDefinition
  - group: 'admissionregistration.k8s.io'
    kind: MutatingWebhookConfiguration

  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false

  roles:
  # A role which provides read-only access to all applications in the project
  - name: read-only
    description: Read-only privileges to hello-world
    policies:
    - p, proj:hello-world:read-only, applications, get, hello-world/*, allow
    groups:
    - hello-world
